-- Deploy emapic:country_names_es to pg

BEGIN;

	ALTER TABLE base_layers.countries ADD COLUMN name_es VARCHAR(254);

	UPDATE base_layers.countries SET name='Andorra', name_es='Andorra' WHERE gid = 7;
	UPDATE base_layers.countries SET name='United Arab Emirates', name_es='Emiratos Árabes Unidos' WHERE gid = 8;
	UPDATE base_layers.countries SET name='Afghanistan', name_es='Afganistán' WHERE gid = 2;
	UPDATE base_layers.countries SET name='Antigua and Barbuda', name_es='Antigua y Barbuda' WHERE gid = 15;
	UPDATE base_layers.countries SET name='Anguilla', name_es='Anguila' WHERE gid = 4;
	UPDATE base_layers.countries SET name='Albania', name_es='Albania' WHERE gid = 5;
	UPDATE base_layers.countries SET name='Armenia', name_es='Armenia' WHERE gid = 10;
	UPDATE base_layers.countries SET name='Angola', name_es='Angola' WHERE gid = 3;
	UPDATE base_layers.countries SET name='Antarctica', name_es='Antártida' WHERE gid = 12;
	UPDATE base_layers.countries SET name='Argentina', name_es='Argentina' WHERE gid = 9;
	UPDATE base_layers.countries SET name='American Samoa', name_es='Samoa Americana' WHERE gid = 11;
	UPDATE base_layers.countries SET name='Austria', name_es='Austria' WHERE gid = 17;
	UPDATE base_layers.countries SET name='Australia', name_es='Australia' WHERE gid = 16;
	UPDATE base_layers.countries SET name='Aruba', name_es='Aruba' WHERE gid = 1;
	UPDATE base_layers.countries SET name='Åland', name_es='Åland' WHERE gid = 6;
	UPDATE base_layers.countries SET name='Azerbaijan', name_es='Azerbaiyán' WHERE gid = 18;
	UPDATE base_layers.countries SET name='Bosnia and Herzegovina', name_es='Bosnia y Herzegovina' WHERE gid = 27;
	UPDATE base_layers.countries SET name='Barbados', name_es='Barbados' WHERE gid = 34;
	UPDATE base_layers.countries SET name='Bangladesh', name_es='Bangladesh' WHERE gid = 23;
	UPDATE base_layers.countries SET name='Belgium', name_es='Bélgica' WHERE gid = 20;
	UPDATE base_layers.countries SET name='Burkina Faso', name_es='Burkina Faso' WHERE gid = 22;
	UPDATE base_layers.countries SET name='Bulgaria', name_es='Bulgaria' WHERE gid = 24;
	UPDATE base_layers.countries SET name='Bahrain', name_es='Baréin' WHERE gid = 25;
	UPDATE base_layers.countries SET name='Burundi', name_es='Burundi' WHERE gid = 19;
	UPDATE base_layers.countries SET name='Benin', name_es='Benín' WHERE gid = 21;
	UPDATE base_layers.countries SET name='St-Barthélemy', name_es='San Bartolomé' WHERE gid = 28;
	UPDATE base_layers.countries SET name='Bermuda', name_es='Bermudas' WHERE gid = 31;
	UPDATE base_layers.countries SET name='Brunei', name_es='Brunéi' WHERE gid = 35;
	UPDATE base_layers.countries SET name='Bolivia', name_es='Bolivia' WHERE gid = 32;
	UPDATE base_layers.countries SET name='Brazil', name_es='Brasil' WHERE gid = 33;
	UPDATE base_layers.countries SET name='Bahamas', name_es='Bahamas' WHERE gid = 26;
	UPDATE base_layers.countries SET name='Bhutan', name_es='Bután' WHERE gid = 36;
	UPDATE base_layers.countries SET name='Botswana', name_es='Botsuana' WHERE gid = 37;
	UPDATE base_layers.countries SET name='Belarus', name_es='Bielorrusia' WHERE gid = 29;
	UPDATE base_layers.countries SET name='Belize', name_es='Belice' WHERE gid = 30;
	UPDATE base_layers.countries SET name='Canada', name_es='Canadá' WHERE gid = 39;
	UPDATE base_layers.countries SET name='Democratic Republic of Congo', name_es='República Democrática del Congo' WHERE gid = 45;
	UPDATE base_layers.countries SET name='Central African Republic', name_es='República Centroafricana' WHERE gid = 38;
	UPDATE base_layers.countries SET name='Congo', name_es='Congo' WHERE gid = 46;
	UPDATE base_layers.countries SET name='Switzerland', name_es='Suiza' WHERE gid = 40;
	UPDATE base_layers.countries SET name='Côte d''Ivoire', name_es='Costa de Marfil' WHERE gid = 43;
	UPDATE base_layers.countries SET name='Cook Islands', name_es='Islas Cook' WHERE gid = 47;
	UPDATE base_layers.countries SET name='Chile', name_es='Chile' WHERE gid = 41;
	UPDATE base_layers.countries SET name='Cameroon', name_es='Camerún' WHERE gid = 44;
	UPDATE base_layers.countries SET name='China', name_es='China' WHERE gid = 42;
	UPDATE base_layers.countries SET name='Colombia', name_es='Colombia' WHERE gid = 48;
	UPDATE base_layers.countries SET name='Costa Rica', name_es='Costa Rica' WHERE gid = 51;
	UPDATE base_layers.countries SET name='Cuba', name_es='Cuba' WHERE gid = 52;
	UPDATE base_layers.countries SET name='Cape Verde', name_es='Cabo Verde' WHERE gid = 50;
	UPDATE base_layers.countries SET name='Curaçao', name_es='Curazao' WHERE gid = 53;
	UPDATE base_layers.countries SET name='Cyprus', name_es='Chipre' WHERE gid = 56;
	UPDATE base_layers.countries SET name='Czech Republic', name_es='República Checa' WHERE gid = 57;
	UPDATE base_layers.countries SET name='Germany', name_es='Alemania' WHERE gid = 58;
	UPDATE base_layers.countries SET name='Djibouti', name_es='Yibuti' WHERE gid = 59;
	UPDATE base_layers.countries SET name='Denmark', name_es='Dinamarca' WHERE gid = 61;
	UPDATE base_layers.countries SET name='Dominica', name_es='Dominica' WHERE gid = 60;
	UPDATE base_layers.countries SET name='Dominican Republic', name_es='República Dominicana' WHERE gid = 62;
	UPDATE base_layers.countries SET name='Algeria', name_es='Argelia' WHERE gid = 63;
	UPDATE base_layers.countries SET name='Ecuador', name_es='Ecuador' WHERE gid = 64;
	UPDATE base_layers.countries SET name='Estonia', name_es='Estonia' WHERE gid = 68;
	UPDATE base_layers.countries SET name='Egypt', name_es='Egipto' WHERE gid = 65;
	UPDATE base_layers.countries SET name='W. Sahara', name_es='Sahara Occidental' WHERE gid = 186;
	UPDATE base_layers.countries SET name='Eritrea', name_es='Eritrea' WHERE gid = 66;
	UPDATE base_layers.countries SET name='Spain', name_es='España' WHERE gid = 67;
	UPDATE base_layers.countries SET name='Ethiopia', name_es='Etiopía' WHERE gid = 69;
	UPDATE base_layers.countries SET name='Finland', name_es='Finlandia' WHERE gid = 70;
	UPDATE base_layers.countries SET name='Fiji', name_es='Fiyi' WHERE gid = 71;
	UPDATE base_layers.countries SET name='Falkland Islands', name_es='Islas Malvinas' WHERE gid = 72;
	UPDATE base_layers.countries SET name='Micronesia', name_es='Micronesia' WHERE gid = 75;
	UPDATE base_layers.countries SET name='Faeroe Islands', name_es='Islas Feroe' WHERE gid = 74;
	UPDATE base_layers.countries SET name='France', name_es='Francia' WHERE gid = 73;
	UPDATE base_layers.countries SET name='Gabon', name_es='Gabón' WHERE gid = 76;
	UPDATE base_layers.countries SET name='United Kingdom', name_es='Reino Unido' WHERE gid = 77;
	UPDATE base_layers.countries SET name='Grenada', name_es='Granada' WHERE gid = 86;
	UPDATE base_layers.countries SET name='Georgia', name_es='Georgia' WHERE gid = 78;
	UPDATE base_layers.countries SET name='Guernsey', name_es='Guernsey' WHERE gid = 79;
	UPDATE base_layers.countries SET name='Ghana', name_es='Ghana' WHERE gid = 80;
	UPDATE base_layers.countries SET name='Greenland', name_es='Groenlandia' WHERE gid = 87;
	UPDATE base_layers.countries SET name='Gambia', name_es='Gambia' WHERE gid = 82;
	UPDATE base_layers.countries SET name='Guinea', name_es='Guinea' WHERE gid = 81;
	UPDATE base_layers.countries SET name='Equatorial Guinea', name_es='Guinea Ecuatorial' WHERE gid = 84;
	UPDATE base_layers.countries SET name='Greece', name_es='Grecia' WHERE gid = 85;
	UPDATE base_layers.countries SET name='South Georgia and South Sandwich Islands', name_es='Islas Georgia del Sur y Sandwich del Sur' WHERE gid = 192;
	UPDATE base_layers.countries SET name='Guatemala', name_es='Guatemala' WHERE gid = 88;
	UPDATE base_layers.countries SET name='Guam', name_es='Guam' WHERE gid = 89;
	UPDATE base_layers.countries SET name='Guinea-Bissau', name_es='Guinea-Bisáu' WHERE gid = 83;
	UPDATE base_layers.countries SET name='Guyana', name_es='Guyana' WHERE gid = 90;
	UPDATE base_layers.countries SET name='Hong Kong', name_es='Hong Kong' WHERE gid = 91;
	UPDATE base_layers.countries SET name='Heard Isle and McDonald Islands', name_es='Islas Heard y McDonald' WHERE gid = 92;
	UPDATE base_layers.countries SET name='Honduras', name_es='Honduras' WHERE gid = 93;
	UPDATE base_layers.countries SET name='Croatia', name_es='Croacia' WHERE gid = 94;
	UPDATE base_layers.countries SET name='Haiti', name_es='Haití' WHERE gid = 95;
	UPDATE base_layers.countries SET name='Hungary', name_es='Hungría' WHERE gid = 96;
	UPDATE base_layers.countries SET name='Indonesia', name_es='Indonesia' WHERE gid = 97;
	UPDATE base_layers.countries SET name='Ireland', name_es='Irlanda' WHERE gid = 102;
	UPDATE base_layers.countries SET name='Israel', name_es='Israel' WHERE gid = 106;
	UPDATE base_layers.countries SET name='Isle of Man', name_es='Isla de Man' WHERE gid = 98;
	UPDATE base_layers.countries SET name='India', name_es='India' WHERE gid = 99;
	UPDATE base_layers.countries SET name='Br. Indian Ocean Ter.', name_es='Territorio Británico del Océano Índico' WHERE gid = 101;
	UPDATE base_layers.countries SET name='Iraq', name_es='Iraq' WHERE gid = 104;
	UPDATE base_layers.countries SET name='Iran', name_es='Irán' WHERE gid = 103;
	UPDATE base_layers.countries SET name='Iceland', name_es='Islandia' WHERE gid = 105;
	UPDATE base_layers.countries SET name='Italy', name_es='Italia' WHERE gid = 107;
	UPDATE base_layers.countries SET name='Jersey', name_es='Jersey' WHERE gid = 109;
	UPDATE base_layers.countries SET name='Jamaica', name_es='Jamaica' WHERE gid = 108;
	UPDATE base_layers.countries SET name='Jordan', name_es='Jordania' WHERE gid = 110;
	UPDATE base_layers.countries SET name='Japan', name_es='Japón' WHERE gid = 111;
	UPDATE base_layers.countries SET name='Kenya', name_es='Kenia' WHERE gid = 114;
	UPDATE base_layers.countries SET name='Kyrgyzstan', name_es='Kirguistán' WHERE gid = 115;
	UPDATE base_layers.countries SET name='Cambodia', name_es='Camboya' WHERE gid = 116;
	UPDATE base_layers.countries SET name='Kiribati', name_es='Kiribati' WHERE gid = 117;
	UPDATE base_layers.countries SET name='Comoros', name_es='Comoras' WHERE gid = 49;
	UPDATE base_layers.countries SET name='St. Kitts and Nevis', name_es='San Cristóbal y Nieves' WHERE gid = 118;
	UPDATE base_layers.countries SET name='Democratic People''s Republic of Korea', name_es='República Popular Democrática de Corea' WHERE gid = 177;
	UPDATE base_layers.countries SET name='Republic of Korea', name_es='República de Corea' WHERE gid = 119;
	UPDATE base_layers.countries SET name='Kuwait', name_es='Kuwait' WHERE gid = 121;
	UPDATE base_layers.countries SET name='Cayman Islands', name_es='Islas Caimán' WHERE gid = 54;
	UPDATE base_layers.countries SET name='Kazakhstan', name_es='Kazajistán' WHERE gid = 113;
	UPDATE base_layers.countries SET name='Lao People''s Democratic Republic', name_es='República Democrática Popular Lao' WHERE gid = 122;
	UPDATE base_layers.countries SET name='Lebanon', name_es='Líbano' WHERE gid = 123;
	UPDATE base_layers.countries SET name='Saint Lucia', name_es='Santa Lucía' WHERE gid = 126;
	UPDATE base_layers.countries SET name='Liechtenstein', name_es='Liechtenstein' WHERE gid = 127;
	UPDATE base_layers.countries SET name='Sri Lanka', name_es='Sri Lanka' WHERE gid = 128;
	UPDATE base_layers.countries SET name='Liberia', name_es='Liberia' WHERE gid = 124;
	UPDATE base_layers.countries SET name='Lesotho', name_es='Lesotho' WHERE gid = 129;
	UPDATE base_layers.countries SET name='Lithuania', name_es='Lituania' WHERE gid = 130;
	UPDATE base_layers.countries SET name='Luxembourg', name_es='Luxemburgo' WHERE gid = 131;
	UPDATE base_layers.countries SET name='Latvia', name_es='Letonia' WHERE gid = 132;
	UPDATE base_layers.countries SET name='Libya', name_es='Libia' WHERE gid = 125;
	UPDATE base_layers.countries SET name='Morocco', name_es='Marruecos' WHERE gid = 135;
	UPDATE base_layers.countries SET name='Monaco', name_es='Mónaco' WHERE gid = 136;
	UPDATE base_layers.countries SET name='Moldova', name_es='Moldavia' WHERE gid = 137;
	UPDATE base_layers.countries SET name='Montenegro', name_es='Montenegro' WHERE gid = 146;
	UPDATE base_layers.countries SET name='St-Martin', name_es='San Martín' WHERE gid = 134;
	UPDATE base_layers.countries SET name='Madagascar', name_es='Madagascar' WHERE gid = 138;
	UPDATE base_layers.countries SET name='Marshall Islands', name_es='Islas Marshall' WHERE gid = 141;
	UPDATE base_layers.countries SET name='Macedonia', name_es='Macedonia' WHERE gid = 142;
	UPDATE base_layers.countries SET name='Mali', name_es='Malí' WHERE gid = 143;
	UPDATE base_layers.countries SET name='Myanmar', name_es='Myanmar' WHERE gid = 145;
	UPDATE base_layers.countries SET name='Mongolia', name_es='Mongolia' WHERE gid = 147;
	UPDATE base_layers.countries SET name='Macao', name_es='Macao' WHERE gid = 133;
	UPDATE base_layers.countries SET name='Northern Mariana Islands', name_es='Islas Marianas del Norte' WHERE gid = 148;
	UPDATE base_layers.countries SET name='Mauritania', name_es='Mauritania' WHERE gid = 150;
	UPDATE base_layers.countries SET name='Montserrat', name_es='Montserrat' WHERE gid = 151;
	UPDATE base_layers.countries SET name='Malta', name_es='Malta' WHERE gid = 144;
	UPDATE base_layers.countries SET name='Mauritius', name_es='Mauricio' WHERE gid = 152;
	UPDATE base_layers.countries SET name='Maldives', name_es='Maldivas' WHERE gid = 139;
	UPDATE base_layers.countries SET name='Malawi', name_es='Malaui' WHERE gid = 153;
	UPDATE base_layers.countries SET name='Mexico', name_es='México' WHERE gid = 140;
	UPDATE base_layers.countries SET name='Malaysia', name_es='Malasia' WHERE gid = 154;
	UPDATE base_layers.countries SET name='Mozambique', name_es='Mozambique' WHERE gid = 149;
	UPDATE base_layers.countries SET name='Namibia', name_es='Namibia' WHERE gid = 155;
	UPDATE base_layers.countries SET name='New Caledonia', name_es='Nueva Caledonia' WHERE gid = 156;
	UPDATE base_layers.countries SET name='Niger', name_es='Níger' WHERE gid = 157;
	UPDATE base_layers.countries SET name='Norfolk Island', name_es='Isla Norfolk' WHERE gid = 158;
	UPDATE base_layers.countries SET name='Nigeria', name_es='Nigeria' WHERE gid = 159;
	UPDATE base_layers.countries SET name='Nicaragua', name_es='Nicaragua' WHERE gid = 160;
	UPDATE base_layers.countries SET name='Netherlands', name_es='Países Bajos' WHERE gid = 162;
	UPDATE base_layers.countries SET name='Norway', name_es='Noruega' WHERE gid = 163;
	UPDATE base_layers.countries SET name='Nepal', name_es='Nepal' WHERE gid = 164;
	UPDATE base_layers.countries SET name='Nauru', name_es='Nauru' WHERE gid = 165;
	UPDATE base_layers.countries SET name='Niue', name_es='Niue' WHERE gid = 161;
	UPDATE base_layers.countries SET name='New Zealand', name_es='Nueva Zealand' WHERE gid = 166;
	UPDATE base_layers.countries SET name='Oman', name_es='Omán' WHERE gid = 167;
	UPDATE base_layers.countries SET name='Panama', name_es='Panamá' WHERE gid = 169;
	UPDATE base_layers.countries SET name='Peru', name_es='Perú' WHERE gid = 171;
	UPDATE base_layers.countries SET name='French Polynesia', name_es='Polinesia Francesa' WHERE gid = 181;
	UPDATE base_layers.countries SET name='Papua New Guinea', name_es='Papúa Nueva Guinea' WHERE gid = 174;
	UPDATE base_layers.countries SET name='Philippines', name_es='Filipinas' WHERE gid = 172;
	UPDATE base_layers.countries SET name='Pakistan', name_es='Pakistán' WHERE gid = 168;
	UPDATE base_layers.countries SET name='Poland', name_es='Polonia' WHERE gid = 175;
	UPDATE base_layers.countries SET name='St. Pierre and Miquelon', name_es='San Pedro y Miquelón' WHERE gid = 200;
	UPDATE base_layers.countries SET name='Pitcairn Islands', name_es='Islas Pitcairn' WHERE gid = 170;
	UPDATE base_layers.countries SET name='Puerto Rico', name_es='Puerto Rico' WHERE gid = 176;
	UPDATE base_layers.countries SET name='Palestine', name_es='Palestina' WHERE gid = 180;
	UPDATE base_layers.countries SET name='Portugal', name_es='Portugal' WHERE gid = 178;
	UPDATE base_layers.countries SET name='Palau', name_es='Palau' WHERE gid = 173;
	UPDATE base_layers.countries SET name='Paraguay', name_es='Paraguay' WHERE gid = 179;
	UPDATE base_layers.countries SET name='Qatar', name_es='Qatar' WHERE gid = 182;
	UPDATE base_layers.countries SET name='Romania', name_es='Rumania' WHERE gid = 183;
	UPDATE base_layers.countries SET name='Serbia', name_es='Serbia' WHERE gid = 201;
	UPDATE base_layers.countries SET name='Russia', name_es='Rusia' WHERE gid = 184;
	UPDATE base_layers.countries SET name='Rwanda', name_es='Rwanda' WHERE gid = 185;
	UPDATE base_layers.countries SET name='Saudi Arabia', name_es='Arabia Saudita' WHERE gid = 187;
	UPDATE base_layers.countries SET name='Solomon Islands', name_es='Islas Salomón' WHERE gid = 194;
	UPDATE base_layers.countries SET name='Seychelles', name_es='Seychelles' WHERE gid = 209;
	UPDATE base_layers.countries SET name='Sudan', name_es='Sudán' WHERE gid = 188;
	UPDATE base_layers.countries SET name='Sweden', name_es='Suecia' WHERE gid = 206;
	UPDATE base_layers.countries SET name='Singapore', name_es='Singapur' WHERE gid = 191;
	UPDATE base_layers.countries SET name='Saint Helena', name_es='Santa Helena' WHERE gid = 193;
	UPDATE base_layers.countries SET name='Slovenia', name_es='Eslovenia' WHERE gid = 205;
	UPDATE base_layers.countries SET name='Slovakia', name_es='Eslovaquia' WHERE gid = 204;
	UPDATE base_layers.countries SET name='Sierra Leone', name_es='Sierra Leona' WHERE gid = 195;
	UPDATE base_layers.countries SET name='San Marino', name_es='San Marino' WHERE gid = 197;
	UPDATE base_layers.countries SET name='Senegal', name_es='Senegal' WHERE gid = 190;
	UPDATE base_layers.countries SET name='Somalia', name_es='Somalia' WHERE gid = 199;
	UPDATE base_layers.countries SET name='Suriname', name_es='Surinam' WHERE gid = 203;
	UPDATE base_layers.countries SET name='South Sudan', name_es='Sudán del Sur' WHERE gid = 189;
	UPDATE base_layers.countries SET name='São Tomé and Principe', name_es='Santo Tomé y Príncipe' WHERE gid = 202;
	UPDATE base_layers.countries SET name='El Salvador', name_es='El Salvador' WHERE gid = 196;
	UPDATE base_layers.countries SET name='Sint Maarten', name_es='Sint Maarten' WHERE gid = 208;
	UPDATE base_layers.countries SET name='Syria', name_es='Siria' WHERE gid = 210;
	UPDATE base_layers.countries SET name='Swaziland', name_es='Swazilandia' WHERE gid = 207;
	UPDATE base_layers.countries SET name='Turks and Caicos Islands', name_es='Islas Turcas y Caicos' WHERE gid = 211;
	UPDATE base_layers.countries SET name='Chad', name_es='Chad' WHERE gid = 212;
	UPDATE base_layers.countries SET name='French Southern Antarctic Lands', name_es='Tierras Australes Francesas' WHERE gid = 14;
	UPDATE base_layers.countries SET name='Togo', name_es='Togo' WHERE gid = 213;
	UPDATE base_layers.countries SET name='Thailand', name_es='Tailandia' WHERE gid = 214;
	UPDATE base_layers.countries SET name='Tajikistan', name_es='Tayikistán' WHERE gid = 215;
	UPDATE base_layers.countries SET name='Timor-Leste', name_es='Timor Oriental' WHERE gid = 217;
	UPDATE base_layers.countries SET name='Turkmenistan', name_es='Turkmenistán' WHERE gid = 216;
	UPDATE base_layers.countries SET name='Tunisia', name_es='Túnez' WHERE gid = 220;
	UPDATE base_layers.countries SET name='Tonga', name_es='Tonga' WHERE gid = 218;
	UPDATE base_layers.countries SET name='Turkey', name_es='Turquía' WHERE gid = 221;
	UPDATE base_layers.countries SET name='Trinidad and Tobago', name_es='Trinidad y Tobago' WHERE gid = 219;
	UPDATE base_layers.countries SET name='Taiwan', name_es='Taiwán' WHERE gid = 222;
	UPDATE base_layers.countries SET name='Tanzania', name_es='Tanzania' WHERE gid = 223;
	UPDATE base_layers.countries SET name='Ukraine', name_es='Ucrania' WHERE gid = 225;
	UPDATE base_layers.countries SET name='Uganda', name_es='Uganda' WHERE gid = 224;
	UPDATE base_layers.countries SET name='United States', name_es='Estados Unidos' WHERE gid = 227;
	UPDATE base_layers.countries SET name='Uruguay', name_es='Uruguay' WHERE gid = 226;
	UPDATE base_layers.countries SET name='Uzbekistan', name_es='Uzbekistán' WHERE gid = 228;
	UPDATE base_layers.countries SET name='Vatican', name_es='Vaticano' WHERE gid = 229;
	UPDATE base_layers.countries SET name='St. Vincent and Grenadines', name_es='San Vicente y las Granadinas' WHERE gid = 230;
	UPDATE base_layers.countries SET name='Venezuela', name_es='Venezuela' WHERE gid = 231;
	UPDATE base_layers.countries SET name='British Virgin Islands', name_es='Islas Vírgenes Británicas' WHERE gid = 232;
	UPDATE base_layers.countries SET name='U.S. Virgin Islands', name_es='Islas Vírgenes de los EE.UU.' WHERE gid = 233;
	UPDATE base_layers.countries SET name='Vietnam', name_es='Vietnam' WHERE gid = 234;
	UPDATE base_layers.countries SET name='Vanuatu', name_es='Vanuatu' WHERE gid = 235;
	UPDATE base_layers.countries SET name='Wallis and Futuna', name_es='Wallis y Futuna' WHERE gid = 236;
	UPDATE base_layers.countries SET name='Samoa', name_es='Samoa' WHERE gid = 237;
	UPDATE base_layers.countries SET name='Yemen', name_es='Yemen' WHERE gid = 238;
	UPDATE base_layers.countries SET name='South Africa', name_es='Sudáfrica' WHERE gid = 239;
	UPDATE base_layers.countries SET name='Zambia', name_es='Zambia' WHERE gid = 240;
	UPDATE base_layers.countries SET name='Zimbabwe', name_es='Zimbabwe' WHERE gid = 241;
	UPDATE base_layers.countries SET name='Ashmore and Cartier Islands', name_es='Islas Ashmore y Cartier' WHERE gid = 13;
	UPDATE base_layers.countries SET name='Northern Cyprus', name_es='Norte de Chipre' WHERE gid = 55;
	UPDATE base_layers.countries SET name='Siachen Glacier', name_es='Glaciar Siachen' WHERE gid = 112;
	UPDATE base_layers.countries SET name='Indian Ocean Territories', name_es='Territorios Océano Índico' WHERE gid = 100;
	UPDATE base_layers.countries SET name='Kosovo', name_es='Kosovo' WHERE gid = 120;

COMMIT;
