-- Deploy emapic:update_province_names to pg

BEGIN;

	UPDATE base_layers.provinces SET name = 'Pozesko-Slavonska' WHERE gid = 1652;
	UPDATE base_layers.provinces SET name = 'Puno' WHERE gid = 3111;
	UPDATE base_layers.provinces SET name = 'Cebu Province' WHERE gid = 3134;
	UPDATE base_layers.provinces SET name = 'Cebu City' WHERE gid = 3213;
	UPDATE base_layers.provinces SET name = 'Karonga' WHERE gid = 2854;
	UPDATE base_layers.provinces SET name = 'Cork County' WHERE gid = 1819;
	UPDATE base_layers.provinces SET name = 'Cork City' WHERE gid = 1790;
	UPDATE base_layers.provinces SET name = 'Cotabato Province' WHERE gid = 3189;
	UPDATE base_layers.provinces SET name = 'Cotabato City' WHERE gid = 3218;
	UPDATE base_layers.provinces SET name = 'Daugavpils City' WHERE gid = 2354;
	UPDATE base_layers.provinces SET name = 'Daugavpils Municipality' WHERE gid = 2339;
	UPDATE base_layers.provinces SET name = 'Tirana' WHERE gid = 80;
	UPDATE base_layers.provinces SET name = 'Galway County' WHERE gid = 1799;
	UPDATE base_layers.provinces SET name = 'Galway City' WHERE gid = 1789;
	UPDATE base_layers.provinces SET name = 'Wirral' WHERE gid = 1329;
	UPDATE base_layers.provinces SET name = 'Iloilo Province' WHERE gid = 3147;
	UPDATE base_layers.provinces SET name = 'Iloilo City' WHERE gid = 3217;
	UPDATE base_layers.provinces SET name = 'Isabela Province' WHERE gid = 3164;
	UPDATE base_layers.provinces SET name = 'Isabela City' WHERE gid = 3212;
	UPDATE base_layers.provinces SET name = 'Jekabpils City' WHERE gid = 2343;
	UPDATE base_layers.provinces SET name = 'Jekabpils Municipality' WHERE gid = 2373;
	UPDATE base_layers.provinces SET name = 'Jelgava Municipality' WHERE gid = 2342;
	UPDATE base_layers.provinces SET name = 'Jelgava City' WHERE gid = 2353;
	UPDATE base_layers.provinces SET name = 'Lacin' WHERE gid = 245;
	UPDATE base_layers.provinces SET name = 'Lankaran District' WHERE gid = 219;
	UPDATE base_layers.provinces SET name = 'Lankaran City' WHERE gid = 260;
	UPDATE base_layers.provinces SET name = 'Limerick City' WHERE gid = 1791;
	UPDATE base_layers.provinces SET name = 'Limerick County' WHERE gid = 1811;
	UPDATE base_layers.provinces SET name = 'Maputo Province' WHERE gid = 2818;
	UPDATE base_layers.provinces SET name = 'Maputo City' WHERE gid = 2819;
	UPDATE base_layers.provinces SET name = 'Kiruhura' WHERE gid = 4308;
	UPDATE base_layers.provinces SET name = 'Neutral Zone (Fujairah & Sharjah)' WHERE gid = 107;
	UPDATE base_layers.provinces SET name = 'Neutral Zone (Ajman & Oman)' WHERE gid = 109;
	UPDATE base_layers.provinces SET name = 'Panjshir' WHERE gid = 29;
	UPDATE base_layers.provinces SET name = 'Rasinski' WHERE gid = 3635;
	UPDATE base_layers.provinces SET name = 'Rîbnita' WHERE gid = 2499;
	UPDATE base_layers.provinces SET name = 'Dubăsari' WHERE gid = 2483;
	UPDATE base_layers.provinces SET name = 'Şəki Municipality' WHERE gid = 262;
	UPDATE base_layers.provinces SET name = 'Şəki District' WHERE gid = 239;
	UPDATE base_layers.provinces SET name = 'Strumica' WHERE gid = 2654;
	UPDATE base_layers.provinces SET name = 'Gevgelija' WHERE gid = 2659;
	UPDATE base_layers.provinces SET name = 'Şuşa District' WHERE gid = 247;
	UPDATE base_layers.provinces SET name = 'Şuşa Municipality' WHERE gid = 263;
	UPDATE base_layers.provinces SET name = 'Tashkent Province' WHERE gid = 4472;
	UPDATE base_layers.provinces SET name = 'Tashkent City' WHERE gid = 4473;
	UPDATE base_layers.provinces SET name = 'Daykundi' WHERE gid = 14;
	UPDATE base_layers.provinces SET name = 'Ventspils Municipality' WHERE gid = 2448;
	UPDATE base_layers.provinces SET name = 'Ventspils City' WHERE gid = 2356;
	UPDATE base_layers.provinces SET name = 'Veszprém City' WHERE gid = 1695;
	UPDATE base_layers.provinces SET name = 'Veszprém County' WHERE gid = 1673;
	UPDATE base_layers.provinces SET name = 'Waterford County' WHERE gid = 1787;
	UPDATE base_layers.provinces SET name = 'Waterford City' WHERE gid = 1792;
	UPDATE base_layers.provinces SET name = 'Iż-Żebbuġ' WHERE gid = 2736;
	UPDATE base_layers.provinces SET name = 'Ħaż-Żebbuġ' WHERE gid = 2705;

COMMIT;
