-- Revert emapic:update_province_names from pg

BEGIN;

	UPDATE base_layers.provinces SET name = 'Brodsko-Posavska' WHERE gid = 1652;
	UPDATE base_layers.provinces SET name = 'Callao' WHERE gid = 3111;
	UPDATE base_layers.provinces SET name = 'Cebu' WHERE gid = 3134;
	UPDATE base_layers.provinces SET name = 'Cebu' WHERE gid = 3213;
	UPDATE base_layers.provinces SET name = 'Chitipa' WHERE gid = 2854;
	UPDATE base_layers.provinces SET name = 'Cork' WHERE gid = 1819;
	UPDATE base_layers.provinces SET name = 'Cork' WHERE gid = 1790;
	UPDATE base_layers.provinces SET name = 'Cotabato' WHERE gid = 3189;
	UPDATE base_layers.provinces SET name = 'Cotabato' WHERE gid = 3218;
	UPDATE base_layers.provinces SET name = 'Daugavpils' WHERE gid = 2354;
	UPDATE base_layers.provinces SET name = 'Daugavpils' WHERE gid = 2339;
	UPDATE base_layers.provinces SET name = 'Durrës' WHERE gid = 80;
	UPDATE base_layers.provinces SET name = 'Galway' WHERE gid = 1799;
	UPDATE base_layers.provinces SET name = 'Galway' WHERE gid = 1789;
	UPDATE base_layers.provinces SET name = 'Halton' WHERE gid = 1329;
	UPDATE base_layers.provinces SET name = 'Iloilo' WHERE gid = 3147;
	UPDATE base_layers.provinces SET name = 'Iloilo' WHERE gid = 3217;
	UPDATE base_layers.provinces SET name = 'Isabela' WHERE gid = 3164;
	UPDATE base_layers.provinces SET name = 'Isabela' WHERE gid = 3212;
	UPDATE base_layers.provinces SET name = 'Jekabpils' WHERE gid = 2343;
	UPDATE base_layers.provinces SET name = 'Jekabpils' WHERE gid = 2373;
	UPDATE base_layers.provinces SET name = 'Jelgava' WHERE gid = 2342;
	UPDATE base_layers.provinces SET name = 'Jelgava' WHERE gid = 2353;
	UPDATE base_layers.provinces SET name = 'Lankaran' WHERE gid = 245;
	UPDATE base_layers.provinces SET name = 'Lankaran' WHERE gid = 219;
	UPDATE base_layers.provinces SET name = 'Lankaran' WHERE gid = 260;
	UPDATE base_layers.provinces SET name = 'Limerick' WHERE gid = 1791;
	UPDATE base_layers.provinces SET name = 'Limerick' WHERE gid = 1811;
	UPDATE base_layers.provinces SET name = 'Maputo' WHERE gid = 2818;
	UPDATE base_layers.provinces SET name = 'Maputo' WHERE gid = 2819;
	UPDATE base_layers.provinces SET name = 'Mbarara' WHERE gid = 4308;
	UPDATE base_layers.provinces SET name = 'Neutral Zone' WHERE gid = 107;
	UPDATE base_layers.provinces SET name = 'Neutral Zone' WHERE gid = 109;
	UPDATE base_layers.provinces SET name = 'Parwan' WHERE gid = 29;
	UPDATE base_layers.provinces SET name = 'Pomoravski' WHERE gid = 3635;
	UPDATE base_layers.provinces SET name = 'Rezina' WHERE gid = 2499;
	UPDATE base_layers.provinces SET name = 'Stîngă Nistrului' WHERE gid = 2483;
	UPDATE base_layers.provinces SET name = 'Şəki' WHERE gid = 262;
	UPDATE base_layers.provinces SET name = 'Şəki' WHERE gid = 239;
	UPDATE base_layers.provinces SET name = 'Southeastern' WHERE gid = 2654;
	UPDATE base_layers.provinces SET name = 'Southeastern' WHERE gid = 2659;
	UPDATE base_layers.provinces SET name = 'Şuşa' WHERE gid = 247;
	UPDATE base_layers.provinces SET name = 'Şuşa' WHERE gid = 263;
	UPDATE base_layers.provinces SET name = 'Tashkent' WHERE gid = 4472;
	UPDATE base_layers.provinces SET name = 'Tashkent' WHERE gid = 4473;
	UPDATE base_layers.provinces SET name = 'Uruzgan' WHERE gid = 14;
	UPDATE base_layers.provinces SET name = 'Ventspils' WHERE gid = 2448;
	UPDATE base_layers.provinces SET name = 'Ventspils' WHERE gid = 2356;
	UPDATE base_layers.provinces SET name = 'Veszprém' WHERE gid = 1695;
	UPDATE base_layers.provinces SET name = 'Veszprém' WHERE gid = 1673;
	UPDATE base_layers.provinces SET name = 'Waterford' WHERE gid = 1787;
	UPDATE base_layers.provinces SET name = 'Waterford' WHERE gid = 1792;
	UPDATE base_layers.provinces SET name = 'Żebbuġ' WHERE gid = 2736;
	UPDATE base_layers.provinces SET name = 'Żebbuġ' WHERE gid = 2705;

COMMIT;
